name: PR Agent

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  pr_agent:
    runs-on: ubuntu-latest

    steps:
      - name: PR Agent
        uses: the-pr-agent/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          GOOGLE_AI_STUDIO.GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

          config__model: gemini/gemini-3.5-flash
          config__fallback_models: gemini/gemini-3.5-flash-lite

          github_action_config__auto_review: 'true'
          github_action_config__auto_describe: 'true'
